name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Create dist directory and copy files
      - name: Setup dist directory
        run: |
          mkdir -p dist
          cp index.html dist/
          cp -r js dist/
          cp -r data dist/
      
      # Inject Firebase config into dist/index.html
      - name: Inject Firebase Config
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const html = fs.readFileSync('dist/index.html', 'utf8');
            const firebaseConfig = {
              apiKey: '${{ secrets.FIREBASE_API_KEY }}',
              authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
              projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
              storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
              messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
              appId: '${{ secrets.FIREBASE_APP_ID }}'
            };
            const injectedHtml = html.replace(
              '</head>',
              `<script>window.FIREBASE_CONFIG = '${JSON.stringify(firebaseConfig)}';</script></head>`
            );
            fs.writeFileSync('dist/index.html', injectedHtml);
      
      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist