name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      # Create dist directory
      - name: Setup dist directory
        run: |
          mkdir -p dist
          cp -r js dist/
          cp index.html dist/
      
      # Inject Firebase config into index.html
      - name: Inject Firebase Config
        run: |
          # Create the config object
          CONFIG="{\"apiKey\":\"${{ secrets.FIREBASE_API_KEY }}\",\"authDomain\":\"${{ secrets.FIREBASE_AUTH_DOMAIN }}\",\"projectId\":\"${{ secrets.FIREBASE_PROJECT_ID }}\",\"storageBucket\":\"${{ secrets.FIREBASE_STORAGE_BUCKET }}\",\"messagingSenderId\":\"${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}\",\"appId\":\"${{ secrets.FIREBASE_APP_ID }}\"}"
          
          # Replace the placeholder
          sed -i "s|window.FIREBASE_CONFIG = null;|window.FIREBASE_CONFIG = '$CONFIG';|" dist/index.html
          CONFIG=$(jq -n \
            --arg key "${{ secrets.FIREBASE_API_KEY }}" \
            --arg domain "${{ secrets.FIREBASE_AUTH_DOMAIN }}" \
            --arg project "${{ secrets.FIREBASE_PROJECT_ID }}" \
            --arg bucket "${{ secrets.FIREBASE_STORAGE_BUCKET }}" \
            --arg sender "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" \
            --arg app "${{ secrets.FIREBASE_APP_ID }}" \
            '{
              apiKey: $key,
              authDomain: $domain,
              projectId: $project,
              storageBucket: $bucket,
              messagingSenderId: $sender,
              appId: $app
            }')
          
          # Escape the JSON for JavaScript
          ESCAPED_CONFIG=$(echo "$CONFIG" | jq -R -s -c .)
          
          # Insert the config into index.html
          sed -i "s|</head>|<script>window.FIREBASE_CONFIG = ${ESCAPED_CONFIG};</script></head>|" dist/index.html
      
      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist